pid_e_node: 
  ros__parameters: 
    Kp_steering : 0.8
    Ki_steering : 1.0E-3 
    Kd_steering : 1.0E-3
    error_threshold : 0.15
    integral_max: 1.0E-1
    zero_speed  : 0.0
    max_speed : 0.5 
    min_speed : 0.4 
    max_right_steering : 0.4 
    max_left_steering : -0.4
    Ts : 0.05
