# param: ['package', 'launch_file']

# sensors
gps_launch: ['gps_node', 'gps_package_launch_file.launch.py']
imu_launch: ['imu_node', 'imu_node_launch_file.launch.py']
pid_launch: ['pid_controller', 'pid_controller_launch_file.launch.py']
